[package]
name = "rio"
version = "0.1.0"
authors = ["Theodore Zilist <tzilist@gmail.com>"]

[dependencies]
actix-web = { version = "^0.6", features=["alpn"] }
actix = "0.5"
env_logger = "0.5"
futures = "0.1"
lru = "0.1.7"